# Generated by Django 5.1.3 on 2024-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('isAvailable', models.BooleanField()),
                ('library_id', models.IntegerField()),
                ('place_number', models.IntegerField()),
                ('isBorrowed', models.BooleanField()),
                ('borrowed_person_id', models.IntegerField()),
                ('return_date', models.CharField(max_length=1000)),
                ('isReserved', models.BooleanField()),
                ('reserved_person_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('login', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=1000)),
                ('library_id', models.IntegerField()),
            ],
        ),
    ]
