# Generated by Django 5.1.3 on 2024-12-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_library_remove_book_library_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='place_number',
            new_name='rack_number',
        ),
    ]
