# Generated by Django 5.1.3 on 2024-12-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_place_number_book_rack_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
